### ISSUE TITLE
request-canceled-and-instance-running

### ISSUE THREAD

**Issue by 2803media** [commoncrawl/cc-mrjob#14]
Hi I notice since today that the script seem to cancel the instance before starting the job.

Here is my mrjob.conf (nothing special), the main instance is a m3.medium one
```

runners:
  emr:
    region: eu-west-1
    # Either set the environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    # or set the two variables below
    aws_access_key_id: xxxx
    aws_secret_access_key: xxxx
    # For more control, it's highly recommended to add your key pair
    #key_pair: warc1
    #key_pair_file: warc1.pem
    #ssh_tunnel: true

    instance_type: m1.medium
    master_instance_type: m1.medium
    master_instance_bid_price: '0.1'
    core_instance_bid_price: '0.1'
    num_core_instances: 2

    # EMR comes with Python 2.6 by default -- installing Python 2.7 takes a while but might be necessary
    # We also install packages needed for streaming compressed files from S3 or reading WARC files
    # There's a newer AMI version but it has issues with the released stable mrjob
    image_version: 3.0.4
    interpreter: python2.7
    bootstrap:
    - sudo yum --releasever=2014.09 install -y python27 python27-devel gcc-c++
    - sudo python2.7 get-pip.py#
    - sudo pip2.7 install boto mrjob simplejson warc
    - sudo pip2.7 install https://github.com/commoncrawl/gzipstream/archive/master.zip

```

But the spot instances were canceled before the setup with the message in EC2 console:

`request-canceled-and-instance-running: Your Spot request is canceled, but your instance i-032af1981833bzz28 is still running. `

I don't know if it's an amazon bug or a problem in the mrjob conf file.

Thanks
