### ISSUE TITLE
Cannot run mrjob on EMR

### ISSUE THREAD

**Issue by rubenmarias** [commoncrawl/cc-mrjob#17]
I am trying to run a mrjob over the whole commoncrawl dataset to filter ips and websites and I keep getting the following error: 

```
Error: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:330)
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:543)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:433)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:344)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:162)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:157)
```

Here is the python code i am submitting: 

```python
import sys
import gzip
import os.path as Path
import boto
import warc
import re
from boto.s3.key import Key
from gzipstream import GzipStreamFile
from mrjob.job import MRJob
from mrcc import CCJob

class CCJob(MRJob):
    def configure_options(self):
        sys.stderr.write('configuration started')
        super(CCJob, self).configure_options()
        self.pass_through_option('--runner')
        self.pass_through_option('-r')

   def mapper(self, _, line):
        sys.stderr.write('mapper started')
        # If we're on EC2 or running on a Hadoop cluster, pull files via S3
        if self.options.runner in ['emr', 'hadoop']:
            # Connect to Amazon S3 using anonymous credentials
            conn = boto.connect_s3(anon=True)
            sys.stderr.write('connection started')
            pds = conn.get_bucket('commoncrawl')
            sys.stderr.write('connected to commoncrawl')
            # Start a connection to one of the WARC files
            k = Key(pds, line)
            sys.stderr.write('key done')
            ccfile = warc.WARCFile(fileobj=GzipStreamFile(k))
            sys.stderr.write('retreiving object')
        # If we're local, use files on the local file system
        else:
            line = Path.join(Path.abspath(Path.dirname(__file__)), line)
            print 'Loading local file {}'.format(line)
            ccfile = warc.WARCFile(fileobj=gzip.open(line))

        sys.stderr.write('start processing file')
        for i, record in enumerate(ccfile):
            for key, value in self.process_record(record):
                yield key, value
            self.increment_counter('commoncrawl', 'processed_records', 1)

    def combiner(self, key, value):
        sys.stderr.write('combiner step')
        # use the reducer by default
        for key_val in self.reducer(key, value):
            yield key_val

    def reducer(self, key, value):
         sys.stderr.write('reducer step')
         yield key, value

class ServerCount(CCJob):
  
    def process_record(self, record):
        sys.stderr.write('processing record')

        # we're only interested in the HTTP responses
        if record['WARC-Type'] == 'response':
            yield record.header['WARC-IP-Address'] + '__' + record.header['WARC-Target-URI'], 1
        return
        
if __name__ == '__main__':
    ServerCount.run()
```

I submit it by doing: 
```
python server_count_warc_emr.py -r emr --conf-path mrjob.conf --no-output --output-dir s3://my-bucket input/test-100.warc 
```

where the output-dir is an s3 bucket that I have created.

My mrjob.conf looks like this: 

```
runners:
  emr:
    region: eu-west-1

    instance_type: m1.medium
    num_core_instances: 1
    
    image_version: 3.0.4
    interpreter: python2.7
    bootstrap:
    - sudo yum --releasever=2014.09 install -y python27 python27-devel gcc-c++
    - sudo python2.7 get-pip.py#
    - sudo pip2.7 install boto mrjob simplejson warc
    - sudo pip2.7 install https://github.com/commoncrawl/gzipstream/archive/master.zip 
```
