### ISSUE TITLE
bootstrapping issues

### ISSUE THREAD

**Issue by andresriancho** [commoncrawl/cc-mrjob#25]
I'm using the following configuration:

```
runners:
  emr:
    # Recommended region: us-east-1 (where Common Crawl data lives)
    region: us-east-1

    # Temp directory for mrjob
    cloud_tmp_dir: s3://common-crawl-cognito/tmp/

    # Log access
    ec2_key_pair: emr-common-crawl
    ec2_key_pair_file: emr-common-crawl.pem
    ssh_tunnel: true

    # Connect to a running EMR cluster to launch the job
    cluster_id: j-HDTYXJ68FFQZ

    interpreter: python2.7

    bootstrap:
    - sudo yum install -y python27 python27-pip python27-devel gcc-c++
    - sudo pip-2.7 install --upgrade boto3 botocore mrjob simplejson warc sentry-sdk==0.7.4
    - sudo pip-2.7 install --upgrade https://github.com/commoncrawl/gzipstream/archive/master.zip
```

Launch the process using:

```
cat mrcc.py cognito_research.py | sed "s/from mrcc import CCJob//" > cognito_research_emr.py

python cognito_research_emr.py -r emr --conf-path mrjob.conf --no-output --output-dir s3://common-crawl-cognito/run-001/ input/test-100.warc
```

I'm getting errors saying that `boto3` module is not installed in python.

After trying different things, I ssh'd into the cluster EC2 instances, manually run the commands, run the script again and everything is working.

Any ideas / hints on what could be wrong? I'm a newbie, where do I look for the stdout / stderr of the bootstrap process? (guessing that might be the problem...)
